<a href="https://colab.research.google.com/github/Isoken00/Credit-Card-Fraud-Detection/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREDIT CARD FRAUD DETECTION USING ML

Importing the dependencies

In [3]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [6]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [7]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
# Last 5 rows of the dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
188256,127893.0,-8.852104,-11.509369,0.449332,2.068166,5.423514,-4.506990,-3.722182,-0.343961,-1.255238,...,-1.390078,1.059268,5.788621,1.226642,1.186211,0.584517,1.783203,-0.400900,37.5,0.0
188257,127894.0,1.609287,-0.581437,0.008484,1.655629,-1.162795,-0.938786,-0.287847,-0.124818,0.855258,...,0.373621,0.902301,0.129504,0.858324,-0.281039,-0.628079,0.032977,0.003303,150.0,0.0
188258,127894.0,2.097886,-0.685229,-1.281921,-0.318993,-0.235987,-0.167462,-0.382762,-0.114099,-0.412410,...,-0.136930,0.381340,0.056371,0.740105,0.272978,-0.107836,0.016936,-0.057214,11.5,0.0
188259,127894.0,1.851731,-0.368532,0.157316,1.422273,-0.917616,-0.315417,-0.696940,0.053708,1.206733,...,0.073982,0.288365,0.247731,-0.001908,-0.361825,-0.760861,0.069835,-0.013513,45.0,0.0
188260,127894.0,1.759307,-0.459599,-0.379355,1.665059,-0.555768,-0.275380,-0.174480,0.001335,1.259834,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Dataset Information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188261 entries, 0 to 188260
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    188261 non-null  float64
 1   V1      188261 non-null  float64
 2   V2      188261 non-null  float64
 3   V3      188261 non-null  float64
 4   V4      188261 non-null  float64
 5   V5      188261 non-null  float64
 6   V6      188261 non-null  float64
 7   V7      188261 non-null  float64
 8   V8      188261 non-null  float64
 9   V9      188261 non-null  float64
 10  V10     188261 non-null  float64
 11  V11     188261 non-null  float64
 12  V12     188261 non-null  float64
 13  V13     188260 non-null  float64
 14  V14     188260 non-null  float64
 15  V15     188260 non-null  float64
 16  V16     188260 non-null  float64
 17  V17     188260 non-null  float64
 18  V18     188260 non-null  float64
 19  V19     188260 non-null  float64
 20  V20     188260 non-null  float64
 21  V21     188260 non-null  float64
 22  V22     188260 non-null  float64
 23  V23     188260 non-null  float64
 24  V24     188260 non-null  float64
 25  V25     188260 non-null  float64
 26  V26     188260 non-null  float64
 27  V27     188260 non-null  float64
 28  V28     188260 non-null  float64
 29  Amount  188260 non-null  float64
 30  Class   188260 non-null  float64
dtypes: float64(31)
memory usage: 44.5 MB

In [11]:
# Checking for missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [12]:
#   Distribution of real and fraudulent transaction
credit_card_data['Class'].value_counts()

0.0    187892
1.0       368
Name: Class, dtype: int64

The Dataset Is Highly Unbalanced

0--> Normal Transaction

1--> Fraudulent Transaction

In [13]:
# Seperating the data for analysis
Legit = credit_card_data[credit_card_data.Class == 0]
Fraud = credit_card_data[credit_card_data.Class == 1]

In [14]:
print(Legit.shape)
print(Fraud.shape)

(187892, 31)
(368, 31)

In [16]:
# Statistical measures of the data
Legit.Amount.describe()

count    187892.000000
mean         88.949661
std         247.532742
min           0.000000
25%           5.960000
50%          22.750000
75%          79.000000
max       19656.530000
Name: Amount, dtype: float64

In [17]:
Fraud.Amount.describe()

count     368.000000
mean      115.659891
std       248.444604
min         0.000000
25%         1.000000
50%        11.395000
75%       104.007500
max      2125.870000
Name: Amount, dtype: float64

In [18]:
# Compare the value for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,66928.356710,-0.115473,0.005839,0.398688,0.079599,-0.127383,0.05489,-0.048754,0.021358,0.018046,...,0.023277,-0.020226,-0.06081,-0.018125,0.006229,0.072192,0.008418,0.001399,0.002064,88.949661
1.0,58116.711957,-5.926741,4.330987,-7.884388,4.836685,-4.286202,-1.42407,-6.893932,0.739547,-2.838131,...,0.404833,0.790022,-0.02306,-0.043940,-0.071941,0.080214,0.040915,0.177371,0.050569,115.659891

**UNDERSAMPLING**

Build a sample dataset containing similar distribution of normal and fraudulent transactions

a similar distribution of normal and fraudulent transactions

Number of fraudulent transactions --> 368

In [19]:
legit_sample = Legit.sample(n=368)

Concatenating two DataFrames

In [22]:
new_dataset = pd.concat([legit_sample, Fraud], axis=0)

In [23]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
165529,117491.0,-0.340362,0.814983,0.485907,-0.365913,0.698083,-1.039745,1.203193,-0.624393,0.002697,...,-0.152249,-0.265194,0.148873,0.063198,-1.060213,0.068564,-0.429565,0.058281,1.79,0.0
112132,72526.0,1.331381,-0.407347,0.583222,-0.501637,-1.186158,-1.196555,-0.332429,-0.329411,-1.063399,...,-0.439921,-0.787674,0.151131,0.767439,0.089158,0.877304,-0.049853,0.020803,27.51,0.0
26578,34149.0,-2.830384,-1.437631,1.192068,-0.459457,-0.778949,0.102314,0.712889,0.130140,0.476592,...,-0.026995,0.091646,-0.768046,-0.291327,0.283213,1.062419,0.281932,-0.756640,382.50,0.0
106953,70209.0,0.766512,-1.095266,0.875239,0.375112,-1.258366,0.140694,-0.481270,0.160416,1.239595,...,-0.084968,-0.440206,-0.068612,0.147630,-0.027093,0.951633,-0.059073,0.046170,216.20,0.0
45730,42473.0,1.314249,-0.933226,-0.261099,-0.969678,-0.164030,0.982521,-0.762154,0.259775,-0.477700,...,-0.047657,-0.203255,-0.254032,-1.702853,0.607508,-0.154716,0.011298,-0.008002,67.55,0.0

In [24]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
178208,123525.0,-5.904921,4.439911,-8.631802,7.788684,-4.989580,-1.200144,-7.674060,4.125761,-5.315778,...,1.775030,1.266441,-0.199410,0.014960,-0.000019,0.544210,-1.167566,-1.206354,45.51,1.0
181966,125200.0,-0.769172,1.342212,-2.171454,-0.151513,-0.648374,-0.973504,-1.706658,0.313745,-1.982302,...,-0.036122,-0.753591,-0.047113,0.358493,-0.287407,0.476506,0.250531,0.250987,40.00,1.0
182992,125612.0,1.889618,1.073099,-1.678018,4.173268,1.015516,-0.009389,-0.079706,0.064071,-0.714517,...,0.203728,0.733796,-0.036560,0.334306,0.147171,0.279556,0.031669,0.035883,3.22,1.0
183106,125658.0,0.224414,2.994499,-3.432458,3.986519,3.760233,0.165640,1.099378,-0.654557,-2.435416,...,0.491337,-0.984223,-0.421979,-1.048058,0.726412,0.268625,0.283689,0.419102,0.00,1.0
184379,126219.0,-1.141559,1.927650,-3.905356,-0.073943,-0.044858,-1.756999,-1.217416,0.364563,-2.770148,...,0.102081,-0.531496,-0.328741,0.393100,0.568435,0.786605,-0.146102,0.076211,25.00,1.0

In [25]:
new_dataset['Class'].value_counts()

0.0    368
1.0    368
Name: Class, dtype: int64

In [26]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,68601.755435,-0.360396,0.023011,0.149244,-0.044053,-0.205188,0.155191,0.118541,0.035064,0.032612,...,-0.015238,0.043683,-0.092735,-0.031255,0.021681,0.061018,0.019217,0.020831,-0.033169,115.859565
1.0,58116.711957,-5.926741,4.330987,-7.884388,4.836685,-4.286202,-1.424070,-6.893932,0.739547,-2.838131,...,0.404833,0.790022,-0.023060,-0.043940,-0.071941,0.080214,0.040915,0.177371,0.050569,115.659891

*Splitting the data into features and targets*

In [27]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [28]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
165529  117491.0 -0.340362  0.814983  0.485907 -0.365913  0.698083 -1.039745
112132   72526.0  1.331381 -0.407347  0.583222 -0.501637 -1.186158 -1.196555
26578    34149.0 -2.830384 -1.437631  1.192068 -0.459457 -0.778949  0.102314
106953   70209.0  0.766512 -1.095266  0.875239  0.375112 -1.258366  0.140694
45730    42473.0  1.314249 -0.933226 -0.261099 -0.969678 -0.164030  0.982521
...          ...       ...       ...       ...       ...       ...       ...
178208  123525.0 -5.904921  4.439911 -8.631802  7.788684 -4.989580 -1.200144
181966  125200.0 -0.769172  1.342212 -2.171454 -0.151513 -0.648374 -0.973504
182992  125612.0  1.889618  1.073099 -1.678018  4.173268  1.015516 -0.009389
183106  125658.0  0.224414  2.994499 -3.432458  3.986519  3.760233  0.165640
184379  126219.0 -1.141559  1.927650 -3.905356 -0.073943 -0.044858 -1.756999

              V7        V8        V9  ...       V20       V21       V22  \
165529  1.203193 -0.624393  0.002697  ... -0.071883 -0.152249 -0.265194
112132 -0.332429 -0.329411 -1.063399  ... -0.360108 -0.439921 -0.787674
26578   0.712889  0.130140  0.476592  ...  0.081335 -0.026995  0.091646
106953 -0.481270  0.160416  1.239595  ...  0.286659 -0.084968 -0.440206
45730  -0.762154  0.259775 -0.477700  ...  0.157407 -0.047657 -0.203255
...          ...       ...       ...  ...       ...       ...       ...
178208 -7.674060  4.125761 -5.315778  ... -0.505608  1.775030  1.266441
181966 -1.706658  0.313745 -1.982302  ... -0.102294 -0.036122 -0.753591
182992 -0.079706  0.064071 -0.714517  ... -0.153570  0.203728  0.733796
183106  1.099378 -0.654557 -2.435416  ... -0.200846  0.491337 -0.984223
184379 -1.217416  0.364563 -2.770148  ... -0.250583  0.102081 -0.531496

             V23       V24       V25       V26       V27       V28  Amount
165529  0.148873  0.063198 -1.060213  0.068564 -0.429565  0.058281    1.79
112132  0.151131  0.767439  0.089158  0.877304 -0.049853  0.020803   27.51
26578  -0.768046 -0.291327  0.283213  1.062419  0.281932 -0.756640  382.50
106953 -0.068612  0.147630 -0.027093  0.951633 -0.059073  0.046170  216.20
45730  -0.254032 -1.702853  0.607508 -0.154716  0.011298 -0.008002   67.55
...          ...       ...       ...       ...       ...       ...     ...
178208 -0.199410  0.014960 -0.000019  0.544210 -1.167566 -1.206354   45.51
181966 -0.047113  0.358493 -0.287407  0.476506  0.250531  0.250987   40.00
182992 -0.036560  0.334306  0.147171  0.279556  0.031669  0.035883    3.22
183106 -0.421979 -1.048058  0.726412  0.268625  0.283689  0.419102    0.00
184379 -0.328741  0.393100  0.568435  0.786605 -0.146102  0.076211   25.00

[736 rows x 30 columns]

In [29]:
print(Y)

165529    0.0
112132    0.0
26578     0.0
106953    0.0
45730     0.0
         ...
178208    1.0
181966    1.0
182992    1.0
183106    1.0
184379    1.0
Name: Class, Length: 736, dtype: float64

Split the data into training & testing data

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [33]:
print(X.shape, X_train.shape, X_test.shape)

(736, 30) (588, 30) (148, 30)

**MODEL TRAINING**

*Logistic Regression*

In [34]:
model = LogisticRegression()

In [35]:
# Training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression()

**MODEL EVALUATION**

*Accuracy Score*

In [36]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [38]:
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.9438775510204082

In [41]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test )

In [42]:
print('Accuracy on test data : ', test_data_accuracy)

Accuracy on test data :  0.9324324324324325